## Create a docker compose file to run pytho
services:
  web:
    build: .
    container_name: cv_classifier_backend
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    volumes:
      - .:/usr/src/app
    
  